### ISSUE TITLE
Explanation on backup rotation

### ISSUE THREAD

**Issue by Kidonian** [MoonCactus/scaleway_remote_backup#1]
Hello,
Can you give more detail on how the backup rotation, keyword and maxid work?

From what I try yet, every time I launch the script. I get a new image with an incremented index but the existing one is deleted. 

If it's possible do I keep backup for a Week rotation.

Thanks for the script

**Comment by MoonCactus** [comment]
Actually this is the expected behavior.

The `maxid` is indeed a growing integer. A new backup needs a new name, as the previous one must be kept in parallel for safety _until_ the new one is completed and it then can be deleted.
The script would have to rename the new backup otherwise, and I went the minimal way (i.e. a new name for each backup).

Anyhow, regarding your schedule, I would simply program 7 different calls to the script: one named after each day of the week and which is obviously triggered on that day. Hence the "keyword= monday" would get deleted on the next monday, i.e. one week later.

I did this way because crontabs do what they do very well and the script can be kept clean by NOT re-doing it.

Better even, you could actually program a one-line cron that triggers on each day, but which would use `date +%a` as the token (that is, the name of the day)!

**Comment by MoonCactus** [comment]
You made me add the cronjob for your case in the README.md, thanks :)
Let me know if this is OK for you!

**Comment by Kidonian** [comment]
OK,
I did have the same idea about naming the days but my boss want multiple schedule, daily, weekly and monthly with different retention time.

Your second idea is good, I'll try this way.
Thanks
